### PR TITLE
Allow append to Apache Rat exclusions

### PR DESCRIPTION
**Pull request by grobmeier**
This patch should allow to append additional exclusions from the child parent

### CODE REVIEW

**Comment by grobmeier** [comment]
Usecase: Chainsaw contains *.log files for testing purposes, they cannot have a license. I am not sure if adding *.log is a good idea to the rat config, but maybe it is

**Comment by vy** [comment]
@grobmeier, since this is only a Chainsaw-specific problem, why don't we only add a `**/*.log` exclude there? For instance, [Log4j has several such RAT overrides](/apache/logging-log4j2/blob/2.x/pom.xml#L539).

**Comment by grobmeier** [comment]
Because it didn't work yesterday - I might have done something wrong. After further clean up, the `combine.children="append"` property works as expected, so this PR with using `combine.children="append"` might not be necessary. I assume it could serve as a default though. but not necessary

**Comment by grobmeier** [comment]
Btw, log4j2 also excludes log files: 
https://github.com/apache/logging-log4j2/blob/2.x/pom.xml#L558

**Comment by vy** [comment]
@grobmeier, I am not a big fan of _"can be useful"_ ideas. If it helps with something, let's do it. Otherwise, let's wait until there is a use case. But that is me and this is an innocent change. I leave it up to you. You can either merge or close the PR. Both are fine by me.

**Comment by grobmeier** [comment]
The use case is that almost every use has specialties that needs to be appended, so it makes sense to me to define append in the parent and not in all childs. Is this use case strong enough for you.

**Comment by vy** [comment]
Sounds good, merging.

**Pull request merged**
